/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kyleaolson.cicd;

import org.checkerframework.common.value.qual.IntRange;

public class App {
    private final static String NOT_USED = "";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        someProcessing();
    }

    public static void someProcessing() {
        for (int i = 0; i < 100; i++)
            System.out.println(i);

        if ("a".equals("b"))
            System.out.println("Oh shit");
    }
}
