/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kyleaolson.cicd;

public class App {
    private final static String NOT_USED = "";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
